KB-friendly functions in `Bap.Std`
BinaryAnalysisPlatform/bap pull request #1545
Opened 2022-08-01 20:03 UTC by bmourad01

This PR proposes a KB-friendly interface for a variety of functions that operate over the old BAP 1.x data structures. Initially, this was motivated by needing to use `Program.lift` in a Knowledge computation without resorting to ugly hacks with the toplevel state. To this end we also expose the `Symtab.create` function in the user-facing API.

This change further motivated KB-friendly `Term.{map,filter_map,filter}` operations. Finally, it made sense to also KB-ify the SSA and flatten passes since they create tids and variables using the top-level KB, which may or may not play nicely when we decide to use these in the middle of a Knowledge computation.

2022-08-01 20:27 UTC, ivg requested changes
Looks good, but could you please add the docstrings to modules and functions and get rid of the `begin/end` blocks by refactoring them into functions?

2022-08-01 20:27 UTC, ivg commented on lib/bap/bap.mli
> +        disassembly state [disasm] and callgraph [calls]. *)
a missing `@since` annotation

2022-08-01 20:27 UTC, ivg commented on lib/bap/bap.mli
> +    module KB : sig
You can put a single `@since` to the whole module.

2022-08-01 20:27 UTC, ivg commented on lib/bap/bap.mli
> +      val map : ('a,'b) cls -> 'a t -> f:('b t -> 'b t knowledge) -> 'a t knowledge
needs some minimal documentation

2022-08-01 20:27 UTC, ivg commented on lib/bap/bap.mli
> +    module KB : sig
also, needs the module documentation together with the `since` annotation

2022-08-01 20:27 UTC, ivg commented on lib/bap/bap.mli
> +      val lift : block -> cfg -> sub term knowledge
this definitely needs documentation.

2022-08-01 20:27 UTC, ivg commented on lib/bap_sema/bap_sema_lift.ml
> +    begin concat_map_fst_and_rev blks @@ function
Those begin/end blocks make the code really unreadable. It was already asking for some refactoring so could you please refactor them into functions?

2022-08-02 18:34 UTC, bmourad01 commented
I removed the behavior of `fix_names` when updating with the `sub_t` class, but I'm wondering where this should be noted in the documentation.

2022-08-03 20:29 UTC, ivg approved these changes
Thanks, that's a lot of work and I am very happy that it is finally done, it gives us so many opportunities!

2022-08-03 20:29 UTC, merged